// SPDX-License-Identifier: MIT LICENSE

pragma solidity ^0.8.26;

interface IVRFSystemCallback {
    /**
     * Callback for when a Random Number is delivered
     *
     * @param requestId     Id of the VRF request
     * @param randomNumber   Random number that was generated by the VRF
     */
    function randomNumberCallback(
        uint256 requestId,
        uint256 randomNumber
    ) external;
}
