// SPDX-License-Identifier: MIT LICENSE

pragma solidity ^0.8.9;

import "../randomizer/IRandomizer.sol";

/** @title Pirate NFT Mock for testing */
contract RandomizerCallbackMock is IRandomizerCallback {
    /// Event to emit to test random receive
    event RandomnessReceived(uint256 requestId, uint256 firstWord);

    /**
     * Callback for when the Chainlink request returns
     *
     * @param requestId     Id of the random word request
     * @param randomWords   Random words that were generated by the VRF
     */
    function fulfillRandomWordsCallback(
        uint256 requestId,
        uint256[] memory randomWords
    ) external override {
        emit RandomnessReceived(requestId, randomWords[0]);
    }
}
